version: '3.3'

services:
  jenkins:
    build:
      context: ./master
    container_name: jenkins-docker
    ports:
      - 80:8080
      - 50000:50000
    volumes:
      - /home/ec2-user/jenkins_home:/var/jenkins_home
      - ./casc_configs:/var/jenkins_conf
    secrets:
      - github
      - adminpw
      - agent-key
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_conf
secrets:
  github:
    file: /home/ec2-user/passwords/github
  adminpw:
    file: /home/ec2-user/passwords/adminpw
  agent-key:
    file: /home/ec2-user/passwords/agent-key

